// scripts/bundle.ts — orchestrate building one product into a single Windows
// .exe. Usage: bun scripts/bundle.ts <sniro|de-vincho>
//
//   1. pnpm -F <slug> build (with VITE_LLM_BASE_URL=/api/llm so the client
//      talks to the launcher's proxy at runtime).
//   2. Stage dist/ into scripts/launcher/embedded.<slug>.assets/, patching
//      index.html to pull in /__app/config.js before the app bundle.
//   3. Emit scripts/launcher/embedded.<slug>.ts — one `import … with { type:
//      "file" }` per staged asset + a manifest mapping URL path → virtual path.
//   4. Point scripts/launcher/embedded.active.ts at the just-emitted manifest.
//   5. Run `bun build --compile --target=bun-windows-x64 --outfile=out/<slug>.exe
//      scripts/launcher.ts`. No --bytecode (oven-sh/bun#18416).

import path from "node:path";
import { spawnSync } from "node:child_process";
import fs from "node:fs";

const VALID_SLUGS = new Set(["sniro", "de-vincho"]);

const HEADLINES: Record<string, string> = {
  sniro: "העוזר החכם של צוות שניר",
  "de-vincho": "דה וינצ'ו — עוזר מידע",
};

function die(msg: string): never {
  console.error(`[bundle] ${msg}`);
  process.exit(1);
}

const slug = process.argv[2];
if (!slug || !VALID_SLUGS.has(slug)) {
  die(`usage: bun scripts/bundle.ts <${[...VALID_SLUGS].join("|")}>`);
}

const repoRoot = path.resolve(import.meta.dir, "..");
const appDist = path.join(repoRoot, "apps", slug, "dist");
const stageRoot = path.join(repoRoot, "scripts", "launcher");
const stageAssets = path.join(stageRoot, `embedded.${slug}.assets`);
const manifestTs = path.join(stageRoot, `embedded.${slug}.ts`);
const activeTs = path.join(stageRoot, "embedded.active.ts");
const outDir = path.join(repoRoot, "out");
const exePath = path.join(outDir, `${slug}.exe`);

console.log(`[bundle] slug=${slug}`);

// 1. Vite build
console.log(`[bundle] pnpm -F ${slug} build`);
// shell: true so Windows can resolve pnpm.cmd / bun.exe via PATH the same
// way macOS / Linux find pnpm and bun. Without it, spawnSync only matches
// bare executables on Windows and fails on .cmd shims.
const useShell = process.platform === "win32";
const buildRes = spawnSync("pnpm", ["-F", slug, "build"], {
  cwd: repoRoot,
  env: {
    ...process.env,
    VITE_LLM_BASE_URL: "/api/llm",
    VITE_LLM_MODEL: "__RUNTIME__",
    VITE_LLM_API_KEY: "",
  },
  stdio: "inherit",
  shell: useShell,
});
if (buildRes.status !== 0) die(`pnpm build failed with status ${buildRes.status}`);
if (!fs.existsSync(appDist)) die(`expected ${appDist} to exist after build`);

// 2. Stage dist into scripts/launcher/embedded.<slug>.assets/, recursively.
fs.rmSync(stageAssets, { recursive: true, force: true });
fs.mkdirSync(stageAssets, { recursive: true });

const staged: { urlPath: string; relAssetPath: string }[] = [];

function walk(dir: string): void {
  for (const name of fs.readdirSync(dir)) {
    const src = path.join(dir, name);
    const stat = fs.statSync(src);
    const rel = path.relative(appDist, src);
    if (stat.isDirectory()) {
      walk(src);
      continue;
    }
    const urlPath = "/" + rel.split(path.sep).join("/");
    const dest = path.join(stageAssets, rel);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(src, dest);
    staged.push({ urlPath, relAssetPath: rel.split(path.sep).join("/") });
  }
}
walk(appDist);

// Patch index.html to load /__app/config.js before the app module script.
const indexPath = path.join(stageAssets, "index.html");
if (!fs.existsSync(indexPath)) {
  die("expected index.html in dist — Vite build shape changed?");
}
let html = fs.readFileSync(indexPath, "utf8");
const moduleTagRe = /<script\s+type="module"/i;
if (!moduleTagRe.test(html)) {
  die('could not find <script type="module"...> in index.html');
}
const CONFIG_TAG = '<script src="/__app/config.js"></script>\n    ';
html = html.replace(moduleTagRe, `${CONFIG_TAG}<script type="module"`);
fs.writeFileSync(indexPath, html);

// 3. Emit the embedded.<slug>.ts manifest module.
staged.sort((a, b) => a.urlPath.localeCompare(b.urlPath));

const identOf = (s: string): string =>
  "f_" + s.replace(/[^a-zA-Z0-9]/g, "_");

const imports: string[] = [];
const entries: string[] = [];
for (const item of staged) {
  const ident = identOf(item.relAssetPath);
  imports.push(
    `import ${ident} from "./embedded.${slug}.assets/${item.relAssetPath}" with { type: "file" };`,
  );
  entries.push(`  ${JSON.stringify(item.urlPath)}: ${ident},`);
}

const manifestSrc =
  `// Generated by scripts/bundle.ts. Do not edit by hand.\n\n` +
  `${imports.join("\n")}\n\n` +
  `export const SLUG = ${JSON.stringify(slug)};\n` +
  `export const HEADLINE = ${JSON.stringify(HEADLINES[slug])};\n` +
  `export const ENV_FILENAME = ${JSON.stringify(`${slug}.env`)};\n\n` +
  `const EMBEDDED: Record<string, string> = {\n${entries.join("\n")}\n};\n` +
  `export default EMBEDDED;\n`;
fs.writeFileSync(manifestTs, manifestSrc);

// 4. Repoint the stable entry to the fresh manifest.
fs.writeFileSync(
  activeTs,
  `// Generated by scripts/bundle.ts. Re-exports the current slug's manifest.\n` +
    `export { default } from "./embedded.${slug}";\n` +
    `export { SLUG, HEADLINE, ENV_FILENAME } from "./embedded.${slug}";\n`,
);

console.log(`[bundle] staged ${staged.length} assets → ${stageAssets}`);

// 5. Cross-compile the single-file Windows executable.
fs.mkdirSync(outDir, { recursive: true });
console.log(`[bundle] bun build --compile → ${exePath}`);
const compileRes = spawnSync(
  "bun",
  [
    "build",
    "--compile",
    "--target=bun-windows-x64",
    "--outfile",
    exePath,
    "scripts/launcher.ts",
  ],
  { cwd: repoRoot, stdio: "inherit", shell: useShell },
);
if (compileRes.status !== 0) die(`bun build --compile failed (${compileRes.status})`);

const size = fs.statSync(exePath).size;
console.log(
  `[bundle] done: ${path.relative(repoRoot, exePath)} (${(size / 1024 / 1024).toFixed(1)} MB)`,
);
