#!/usr/bin/env node
// scripts/safe-deploy.mjs — produce a minimal runtime bundle for the
// scan-safe path. The output directory contains ONLY what `node serve.mjs`
// needs to run: the built dist/, the static server (path-rewritten so it
// looks for files alongside itself), and the user's .env.local.
//
// Crucially the bundle has NO node_modules and NO .pnpm-store. After a
// fresh build, esbuild.exe (~10 MB unsigned, Go-compiled) and rollup's
// .node native addons sit inside node_modules — both are widely-used and
// usually fine, but they're unsigned and can trip strict AV/EDR setups.
// The runtime doesn't need any of it (serve-static.mjs imports only
// `node:*` built-ins), so the right move is to leave them on the build
// machine and ship a clean bundle to the target.
//
// Workflow:
//   1. (connected machine) node scripts/safe-build.mjs <slug>
//   2. (connected machine) node scripts/safe-deploy.mjs <slug>
//   3. transfer the produced deploy-<slug>/ directory to the Windows host
//   4. (target machine) install Node 20+, then in deploy-<slug>/:
//        node serve.mjs
//
// Usage:
//   node scripts/safe-deploy.mjs <sniro|de-vincho> [target-dir]

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");

const VALID = new Set(["sniro", "de-vincho"]);
const slug = process.argv[2];
if (!slug || !VALID.has(slug)) {
  console.error(
    `usage: node scripts/safe-deploy.mjs <${[...VALID].join("|")}> [target-dir]`,
  );
  process.exit(1);
}

const targetDir = path.resolve(
  process.argv[3] || path.join(repoRoot, `deploy-${slug}`),
);

const distSrc = path.join(repoRoot, "apps", slug, "dist");
const envSrc = path.join(repoRoot, "apps", slug, ".env.local");
const scriptSrc = path.join(repoRoot, "scripts", "serve-static.mjs");

if (!fs.existsSync(path.join(distSrc, "index.html"))) {
  console.error(
    `error: ${distSrc}/index.html not found.\n` +
      `Run \`node scripts/safe-build.mjs ${slug}\` first.`,
  );
  process.exit(1);
}

// Adapt serve-static.mjs to the flat bundle layout. Three precise edits:
//   (a) bake in the slug so the deployed script needs no argv
//   (b) repoint distDir to dist/ alongside the script
//   (c) repoint envPath to .env.local alongside the script
// Each edit asserts on the source string so a future refactor of
// serve-static.mjs that changes those lines fails loudly here instead of
// silently shipping a broken serve.mjs.
const ORIG_SLUG = "const slug = process.argv[2];";
const ORIG_DIST = 'const distDir = path.join(repoRoot, "apps", slug, "dist");';
const ORIG_ENV =
  'const envPath = path.join(repoRoot, "apps", slug, ".env.local");';

const serveSrc = fs.readFileSync(scriptSrc, "utf8");
for (const needle of [ORIG_SLUG, ORIG_DIST, ORIG_ENV]) {
  if (!serveSrc.includes(needle)) {
    console.error(
      `error: serve-static.mjs has changed shape — needle not found:\n  ${needle}\n` +
        `Update scripts/safe-deploy.mjs to match.`,
    );
    process.exit(1);
  }
}

// The header has to land AFTER the shebang or ESM will choke on the `#`
// (shebangs are only recognized as the first line). Insert right after.
const SHEBANG = "#!/usr/bin/env node\n";
const HEADER =
  `// Deploy build of scripts/serve-static.mjs (slug=${slug}). Generated by\n` +
  `// scripts/safe-deploy.mjs — do not edit by hand. Re-run safe-deploy on\n` +
  `// the source repo to refresh.\n\n`;
if (!serveSrc.startsWith(SHEBANG)) {
  console.error(`error: serve-static.mjs no longer starts with the expected shebang.`);
  process.exit(1);
}
const serveOut =
  SHEBANG +
  HEADER +
  serveSrc
    .slice(SHEBANG.length)
    .replace(ORIG_SLUG, `const slug = ${JSON.stringify(slug)};`)
    .replace(ORIG_DIST, 'const distDir = path.join(__dirname, "dist");')
    .replace(ORIG_ENV, 'const envPath = path.join(__dirname, ".env.local");');

// Wipe and recreate target. Refuse a target that already contains
// non-bundle content so we don't accidentally overwrite the wrong folder.
if (fs.existsSync(targetDir)) {
  const expected = new Set(["serve.mjs", "dist", ".env.local", "README.txt"]);
  const present = fs.readdirSync(targetDir);
  const surprises = present.filter((n) => !expected.has(n));
  if (surprises.length) {
    console.error(
      `error: target ${targetDir} contains files that don't match the deploy ` +
        `shape: ${surprises.join(", ")}. Refusing to overwrite. Pass an empty ` +
        `path or remove ${targetDir} first.`,
    );
    process.exit(1);
  }
  fs.rmSync(targetDir, { recursive: true, force: true });
}
fs.mkdirSync(targetDir, { recursive: true });

copyDir(distSrc, path.join(targetDir, "dist"));
fs.writeFileSync(path.join(targetDir, "serve.mjs"), serveOut);

if (fs.existsSync(envSrc)) {
  fs.copyFileSync(envSrc, path.join(targetDir, ".env.local"));
} else {
  // Bare template if the operator hasn't configured anything yet — the
  // server will start in "configuration required" mode either way.
  fs.writeFileSync(
    path.join(targetDir, ".env.local"),
    `# ${slug} runtime config — edit before running serve.mjs.\n` +
      `LLM_UPSTREAM=\n` +
      `VITE_LLM_API_KEY=\n` +
      `VITE_LLM_MODEL=\n` +
      `VITE_PORT=\n`,
  );
}

const defaultPort = slug === "de-vincho" ? 5174 : 5173;
fs.writeFileSync(
  path.join(targetDir, "README.txt"),
  `${slug} — scan-safe deploy bundle\n` +
    `${"=".repeat(36 + slug.length)}\n\n` +
    `Contents (this is everything needed at runtime):\n` +
    `  serve.mjs       Plain Node 20+ HTTP server. Static + LLM proxy.\n` +
    `  dist/           Built app — fully self-contained.\n` +
    `  .env.local      Your config (LLM_UPSTREAM, VITE_LLM_API_KEY, etc).\n\n` +
    `What's NOT here, deliberately: node_modules, .pnpm-store, source\n` +
    `code, the Vite/Bun/esbuild build chain. The runtime needs none of\n` +
    `it — serve.mjs imports only Node built-ins. The only executable\n` +
    `that runs on the target is your system node.exe.\n\n` +
    `To run:\n` +
    `  1. Install Node.js 20+ from https://nodejs.org if not already.\n` +
    `  2. Edit .env.local — set LLM_UPSTREAM (your model gateway URL),\n` +
    `     VITE_LLM_API_KEY (if your provider needs one), VITE_LLM_MODEL.\n` +
    `  3. Open a terminal in this folder and run:\n` +
    `       node serve.mjs\n` +
    `  4. Open http://127.0.0.1:${defaultPort}/ in a browser.\n\n` +
    `Security posture (mirrors scripts/launcher/proxy.ts):\n` +
    `  - 127.0.0.1-only bind, no LAN exposure.\n` +
    `  - Strict CSP + nosniff + X-Frame-Options DENY + no-referrer on\n` +
    `    every response.\n` +
    `  - Method allow-list: GET/HEAD/POST/OPTIONS on /api/llm,\n` +
    `    GET/HEAD on static. TRACE/CONNECT/PUT/PATCH return 405.\n` +
    `  - Path traversal blocked (raw, URL-encoded, null bytes,\n` +
    `    backslashes, drive letters, symlinks).\n` +
    `  - Origin/Referer/Cookie + RFC 7230 hop-by-hop headers stripped\n` +
    `    before forwarding to the upstream.\n` +
    `  - Authorization injected server-side from .env.local — the API\n` +
    `    key never reaches the browser bundle.\n` +
    `  - Proxy body capped at 2 MiB (413 on overflow).\n` +
    `  - 120s upstream-headers timeout, then 502.\n`,
);

console.log(`[safe-deploy] ${slug} → ${targetDir}`);
console.log(`[safe-deploy]   serve.mjs   (${serveOut.length} bytes)`);
console.log(
  `[safe-deploy]   dist/       (${countFiles(path.join(targetDir, "dist"))} files, ${formatBytes(dirSize(path.join(targetDir, "dist")))})`,
);
console.log(`[safe-deploy]   .env.local`);
console.log(`[safe-deploy]   README.txt`);
console.log(
  `[safe-deploy] transfer ${path.basename(targetDir)}/ to the target machine, then: \`cd ${path.basename(targetDir)} && node serve.mjs\``,
);

function copyDir(src, dst) {
  fs.mkdirSync(dst, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dst, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else if (entry.isFile()) fs.copyFileSync(s, d);
    // Symlinks are deliberately skipped — we don't want to follow them
    // off-tree, and we don't want to recreate symlinks on the target
    // (Windows symlink semantics are different and require admin).
  }
}

function countFiles(dir) {
  let n = 0;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.isDirectory()) n += countFiles(path.join(dir, e.name));
    else n++;
  }
  return n;
}

function dirSize(dir) {
  let n = 0;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) n += dirSize(p);
    else n += fs.statSync(p).size;
  }
  return n;
}

function formatBytes(n) {
  if (n < 1024) return n + " B";
  if (n < 1024 * 1024) return (n / 1024).toFixed(1) + " KiB";
  return (n / 1024 / 1024).toFixed(1) + " MiB";
}
