#!/usr/bin/env node
// First-run bootstrap. Idempotent — safe to re-run.
//
// What it does:
//   1. Copies .env.example to apps/<slug>/.env.local for each app, only if
//      that file is missing (never clobbers a hand-edited config).
//   2. Sets VITE_PORT in de-vincho's .env.local so the two apps don't fight
//      over port 5173.
//   3. Prints clear next steps in plain English / Hebrew.
//
// Why a script instead of just docs: every new teammate would otherwise
// repeat the same `cp` + `which preset?` dance. The script makes the
// happy path one command on every OS.
//
// Flags:
//   --quiet     Silent on no-op (re-runs after first bootstrap). Used by
//               the package.json `postinstall` hook so a routine
//               `pnpm install` doesn't spam the terminal.

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const QUIET = process.argv.includes("--quiet");

const APPS = [
  { slug: "sniro", port: 5173 },
  { slug: "de-vincho", port: 5174 },
];

const examplePath = path.join(repoRoot, ".env.example");

async function exists(p) {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

async function main() {
  if (!(await exists(examplePath))) {
    console.error(`error: ${examplePath} is missing — has the repo been altered?`);
    process.exit(1);
  }
  const example = await fs.readFile(examplePath, "utf8");

  const created = [];
  const skipped = [];

  for (const { slug, port } of APPS) {
    const target = path.join(repoRoot, "apps", slug, ".env.local");
    if (await exists(target)) {
      skipped.push({ slug, target });
      continue;
    }
    const header =
      `# ${slug} — local env. Git-ignored.\n` +
      `# Generated by \`pnpm bootstrap\` (or the postinstall hook).\n` +
      `# Edit freely; this file is yours.\n` +
      `#\n` +
      `# Pick ONE preset below by uncommenting its block, then \`pnpm dev:${slug}\`.\n` +
      `# Without any preset uncommented, the app still loads — it just shows\n` +
      `# a "configuration required" state until you point it at a model.\n\n`;
    const portLine = port !== 5173 ? `VITE_PORT=${port}\n\n` : "";
    await fs.writeFile(target, header + portLine + example);
    created.push({ slug, target });
  }

  // Quiet mode: when nothing was created (idempotent re-run), say nothing.
  // This keeps `pnpm install` output clean on routine installs.
  if (QUIET && created.length === 0) return;

  console.log("");
  if (created.length) {
    console.log("✓ created:");
    for (const { slug } of created) {
      console.log(`    apps/${slug}/.env.local  (from .env.example)`);
    }
  }
  if (skipped.length && !QUIET) {
    console.log("· left alone (already exist):");
    for (const { slug } of skipped) {
      console.log(`    apps/${slug}/.env.local`);
    }
  }
  console.log("");
  console.log("Ready. Run one of:");
  console.log("  pnpm dev:sniro       → http://localhost:5173");
  console.log("  pnpm dev:de-vincho   → http://localhost:5174");
  console.log("");
  console.log("Open apps/<slug>/.env.local and uncomment a provider preset");
  console.log("(or set your team's gateway URL in VITE_LLM_BASE_URL).");
  console.log("With no preset configured, the UI loads and explains how.");
  console.log("");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
